### ISSUE TITLE
Plan for documentation.

### ISSUE THREAD

**Issue by brenthuisman** [arbor-sim/arbor#1126]
This is a TODO for all things I'd like to update in/about the docs. The word "section" I use to refer to header/grouping on the readthedocs navigation sidebar.

* "How does arbor work?" is about concepts
    * [x] This section now is getting a large number of pages, break out some? A cell section? we can go into detail such as cell types vs morpho/mech/junctions?
    * [x] Rename and reorg Common Types pages. They reflect roughly the content under Concepts>Network Components.
        * [ ] Probes can have their own page, seems important?
        * [x] reflect some of this into Python/C++ API pages, contributes to fixing #474
        * [ ] Update c++ recipe page #1080
    * Cell kinds: 4 hard coded, only cable cell is morphologically detailed.
* [x] Would be nice to have: classindex, functionindex: [Sphinx does not provide this](https://github.com/sphinx-doc/sphinx/issues/3178), just a moduleindex.
    * [x] C++: use doxygen
        * [breathe](https://breathe.readthedocs.io) runs into a [documented issue](https://github.com/sphinx-doc/sphinx/issues/7438). Trouble is, we don't set `-j` for `sphinx-build`, so what's going on?
        * [exhale](https://exhale.readthedocs.io) uses `breathe`, supposedly easier to make indices. Used/created by some of the spack people. However, [trips](https://github.com/sphinx-doc/sphinx/issues/2682) [over](https://github.com/sphinx-doc/sphinx/issues/5187) macros and decorators (CUDA).
    * [x] Python: autodoc. Doesn't do [constants](https://github.com/sphinx-doc/sphinx/issues/1063). Multiple definitions in Sphinx: [There is a proposal to allow them, for synopses](https://github.com/sphinx-doc/sphinx/issues/4981). Having a reference page alongside other documentation refer to the same code makes it a guarantee to have these warnings.
* [x] (user/python) example-section: some lines of increasing complexity: (solves #877 #1107 )
    * cell complexity
    * interconnectivity
    * cell types
    * At minimum, explain how to find and use current examples
        * [x] update existing ones to fix #1129
    - [x] remove all traces of flat_cell_builder
        * ring.py
        * single_cell_builder.py
- stitches (sam)
- cable cell is quite saturated, break out some more? at least in the c++ api
    - cpp_cable_cell.html: TODO: describe other place-able things: current clamps, gap junction sites, threshold potential measurement point.
    - Super clear!
    - explain somewhere painting vs placing.
