### ISSUE TITLE
Add tutorials and examples for SDE

### ISSUE THREAD

**Issue by thorstenhater** [arbor-sim/arbor#1987]
#1884 is about to get merged, we should add a few basic examples at least to 
show how to use it from Python and C++. Also, some standard mechanisms could
be included in a 'stochastic' catalogue.

### TODO

- [x] add a simple example
  - [x] C++
  - [x] Python
- [x] add stochastic catalogue
  - [x] O-U process point source
- [ ] Optional: add tutorial

**Comment by schmitts** [comment]
I can contribute the Graupner-Brunel example.

**Comment by thorstenhater** [comment]
That'd be cool.
